getting these errors
GETTING

Error: A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:
A server/client branch if (typeof window !== 'undefined').
Variable input such as Date.now() or Math.random() which changes each time it's called.
Date formatting in a user's locale which doesn't match the server.
External changing data without sending a snapshot of it along with the HTML.
Invalid HTML tag nesting.
It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

https://react.dev/link/hydration-mismatch

... <RedirectErrorBoundary router={{...}}> <Head> <link> <script> <script> <script> <RootLayout> <html lang="en" className="dark"> <body className="antialiase..." suppressHydrationWarning={true}> ... <LoadingBoundary loading={null}> <HTTPAccessFallbackBoundary notFound={[...]} forbidden={undefined} unauthorized={undefined}> <HTTPAccessFallbackErrorBoundary pathname="/" notFound={[...]} forbidden={undefined} ...> <RedirectBoundary> <RedirectErrorBoundary router={{...}}> <InnerLayoutRouter url="/?monospac..." tree={[...]} cacheNode={{lazyData:null, ...}} ...> <ClientPageRoot Component={function GamePage} searchParams={{...}} params={{}}> <GamePage params={Promise} searchParams={Promise}> <div className="flex flex-col items-center justify-center min-h-screen bg-gradient-to-br fr..."

                          bis_skin_checked="1"
                        >
                          <_c className="w-full max...">
                            <div
                              ref={null}
                              className="rounded-lg border bg-card text-card-foreground w-full max-w-md shadow-2xl"
                              bis_skin_checked="1"
                            >
                              <_c2>
                                <div
                                  ref={null}
                                  className="flex flex-col space-y-1.5 p-6"
                                  bis_skin_checked="1"
                                >
                                  <_c4 className="text-4xl f...">
                                    <div
                                      ref={null}
                                      className="tracking-tight text-4xl font-bold text-primary text-center"
                                      bis_skin_checked="1"
                                    >

                                      Judgement
                                  <_c6 className="text-cente...">
                                    <div
                                      ref={null}
                                      className="text-sm text-center text-muted-foreground pt-2"
                                      bis_skin_checked="1"
                                    >

                                      The virtual card game for remote friends.
                              <_c8>
                                <div
                                  ref={null}
                                  className="p-6 pt-0"
                                  bis_skin_checked="1"
                                >
                                  <form onSubmit={function handleNameSubmit} className="space-y-4">
                                    <div
                                      className="space-y-2"
                                      bis_skin_checked="1"
                                    >
                                    ...
                    ...
      <Toaster>
        <ToastProvider>
          <ToastCollectionProvider scope={undefined}>
            <ToastCollectionProviderProvider scope={undefined} itemMap={Map} collectionRef={{current:null}}>
              <ToastProviderProvider scope={undefined} label="Notification" duration={5000} swipeDirection="right" ...>
                <_c>
                  <ToastViewport ref={null} className="fixed top-...">
                    <DismissableLayerBranch ref={{current:null}} role="region" aria-label="Notificati..." ...>
                      <Primitive.div role="region" aria-label="Notificati..." tabIndex={-1} style={{...}} ...>
                        <div
                          role="region"
                          aria-label="Notifications (F8)"
                          tabIndex={-1}
                          style={{pointerEvents:"none"}}
                          ref={function}
                          bis_skin_checked="1"
                        >
      ...
...
at createUnhandledError (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:879:71) at handleClientError (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1052:56) at console.error (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1191:56) at https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9382:25 at runWithFiberInDEV (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:3501:74) at emitPendingHydrationWarnings (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9381:13) at completeWork (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9455:102) at runWithFiberInDEV (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:3501:131) at completeUnitOfWork (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10233:23) at performUnitOfWork (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10170:28) at workLoopConcurrentByScheduler (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10164:58) at renderRootConcurrent (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10146:71) at performWorkOnRoot (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9784:176) at performWorkOnRootViaSchedulerTask (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10796:9) at MessagePort.performWorkUntilDeadline (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:1952:64) at div (<anonymous>) at _c4 (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/src_5055e907._.js:234:450) at renderEnterName (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/src_5055e907._.js:1015:231) at GamePage (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/src_5055e907._.js:1802:20) at ClientPageRoot (https://9000-idx-studio-1746280355931.cluster-iktsryn7xnhpexlu6255bftka4.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_1a6ee436._.js:2053:50)

and

Failed to copy room code: NotAllowedError: Failed to execute 'writeText' on 'Clipboard': The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.